name: Dockerfile test

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
        version: [1.13, 1.14, 1.15]
        
    name: Build Container
    runs-on: ${{ matrix.os }}

    steps:

    - name: Setup GO version
      uses: actions/setup-go@v3
      with:
          go-version: ${{ matrix.version }}
    
    - name: Git clone
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and Push to DockerHub
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: dockerid21656/updated_go_image:1.0.2

