name: Dockerfile test

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build Container
    runs-on: ubuntu-latest

    steps:
    - name: Git clone
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and Push to DockerHub
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: dockerid21656/updated_go_image:1.0.0

