name: Dockerfile test

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build Container
    runs-on: ubuntu-latest

    steps:
    - name: Git clone
      uses: actions/checkout@v3

    - name: Buid Dockerfile
      run: docker build -t go_image .

    - name: Tag image
      run: docker tag go_image dockerid21656/go_image:0.1.0

    - name: Login to DockerHub
      env:
        USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
    - name: print env
      run: echo $USERNAME

      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Push image to DockerHub
      run: docker push dockerid21656/go_image:0.1.0
